language: java

jdk:
  - openjdk8

branches:
  only:
    - master
    - stable

install: true

before_script:

script: 
  - gradle build 
deploy:
  - provider: script
    skip_cleanup: true
    script: ssh-keyscan -H ftp.umleditor.org >> ~/.ssh/known_hosts; gradle -Drepos_pwd=${repos_pwd} -Drepos_usr=umledi_0 '-Drepos_url=sftp://ftp.umleditor.org' upload
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ssh-keyscan -H ftp.umleditor.org >> ~/.ssh/known_hosts; gradle -Drepos_pwd=${repos_pwd} -Drepos_usr=umledi_0 '-Drepos_url=sftp://ftp.umleditor.org' '-Drelease=' upload
    on:
      branch: stable
